During this tutorial we will demonstrate how to use QuantEcon to solve a Payoff Matrix, as well as find any nash equillibrium values

Don't worry if you are not familiar with Nash Equillibriums, as we will do our best to explain it here.

First, install quantecon using the code below

In [1]:
#!pip install quantecon

import numpy as np
import quantecon.game_theory as gt

Then our next step is to simply assign a name to your matrix, then use the normalformgame function to have quantecon load it in as a game.


In [2]:
matrix = [[(9,3), (1, 6)],
                             [(2, 2), (0, 1)]]
game = gt.NormalFormGame(matrix)
print(game)


2-player NormalFormGame with payoff profile array:
[[[9, 3],  [1, 6]],
 [[2, 2],  [0, 1]]]


You can also create games by creating individual players and then joining them together to form games

This is useful if you want to see how a number of different players stack up against each other.

So first, we will create the players. 

In [3]:
player_A = gt.Player([[9,1], [2, 0]])
player_B = gt.Player([[3, 2], [6, 1]])
player_C = gt.Player([[9, 9], [1, 1]])

Once I have my players set up I can create games.

Here is the same game I created before:

In [4]:
same_game = gt.NormalFormGame((player_A, player_B))
print(same_game)

2-player NormalFormGame with payoff profile array:
[[[9, 3],  [1, 6]],
 [[2, 2],  [0, 1]]]


Here is a different game where I swap player b for a new player c

In [6]:
different_game = gt.NormalFormGame((player_A, player_C))
print(different_game)

2-player NormalFormGame with payoff profile array:
[[[9, 9],  [1, 1]],
 [[2, 9],  [0, 1]]]


Moving into actual game theory, we'll be exaimining the Stag Hunting problem.

In this scenario:
    
    -there are two hunters each trying to catch rabits and stags
    
    -the stag has 10 units of meat and there is only one
       
       -the only way to catch it is to collaborate
    
    -the rabbits are 1 unit of meat each and there are 2 of them
        
        -if you both try to hunt the rabbits you split the rabbits
        
This translates to the following matrix-

In [7]:
stag_hunt = [[(5,5), (0, 2)],
                             [(2, 0), (1, 1)]]

Now we load the matrix into quant econ's normal form game function


In [8]:
stag_hunt_matrix = gt.NormalFormGame(stag_hunt)
print(stag_hunt_matrix)

2-player NormalFormGame with payoff profile array:
[[[5, 5],  [0, 2]],
 [[2, 0],  [1, 1]]]


If I want to see the different players individual matrixes, I can add '.players[]' at the end and put a 0 or a 1 in the brackets in order to see the payoff array for player 1 or player 2

Here is the payoff array for player 1:

In [9]:
stag_hunt_matrix.players[0].payoff_array 

array([[5, 0],
       [2, 1]])

Here is the payoff array for player 2:

In [10]:
stag_hunt_matrix.players[1].payoff_array 

array([[5, 0],
       [2, 1]])

If I want to see what each individuals best response is given the other's response you can use the 'best_response()' function

In the example below, this is showing you player 1's best response given that player 2 chooses choice 1

In [11]:
stag_hunt_matrix.players[0].best_response(0)

0

An alternate way of looking at the same problem is to use the payoff_vector function. 

In [12]:
stag_hunt_matrix.players[0].payoff_vector(0)

array([5, 2])

This also communicates that the best option for player 1 if player 2 chooses choice 1 is to also choose choice 1.

Here is the best response of player 1 should player 2 choose choice 2

In [13]:
stag_hunt_matrix.players[0].best_response(1)

1

If the best response was the same independent of whether player 2 chose choice 1 or choice 2, then that is considered a dominant strategy for player 1.

In this scenario there is no dominant strategy, because it is dependent on the other players move

With regard to game theory there is a concept called a nash equillibrium

This concept describes an outcome where the payoffs for each player are such that neither player has any incentive to deviate from their strategy. Meaning that if we pick an outcome, could either player individually deviate from that outcome to make themselves better off?


This isnt captured by simply looking at the best responses for each player, and thus quantecon has provides us with a function to acquire pure nash equillibriums

As well there are two types of nash equillibrium, mixed and pure, that mean different things, but for now to not complicate things, lets go ahead and find the pure nash equillibrium for the stag hunt:


In [14]:
gt.pure_nash_brute(stag_hunt_matrix)


[(0, 0), (1, 1)]

This result states that the pure nash equlibrium is either, for both players to hunt the stag or both players to hunt the rabbits

This is because if they both agree to hunt the rabbit or the stag, then they cant individually deviate from that choice (knowing the other persons choice remains the same) and be better off. If you know the other person is hunting the stag of rabbit definitively, moving away from that choice can only be harmful. 


To confirm this result is a nash equillibrium we can inspect what the payoff matrix (or use best_response) is for player 2, should player 1 choose to go for choice 1
and what the payoff is for player 1 should player 2 choose choice 1. If both answers are to not deviate then it confirms it as a pure nash equillibrium like the 'pure_nash_brute' function already informed us

In [15]:
stag_hunt_matrix.players[0].payoff_vector(0)


array([5, 2])

In [16]:
stag_hunt_matrix.players[1].payoff_vector(0)

array([5, 2])

The best option is still choice 1 for both parties if the other chooses choice 1, thus it is a pure nash equilibrium.

That concludes this tutorial, if you are interested in the mixed strategy nash equilibrium, although it is not mentioned in this demo, you can find mixed strategy nash equilibriums using the 'support_enumeration' function. 